model_verbosity = "low" # low, medium, high
file_opener = "vscode"
plan_mode_reasoning_effort = "xhigh" # low, medium, high, xhigh
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
writable_roots = ["/home/simone/.cache/", "/home/simone/.npm/", "/home/simone/.storybook/"]
network_access = true

[agents]
max_depth = 2
max_threads = 10

[mcp_servers.basic-memory]
command = "basic-memory"
args = ["mcp", "--project", "video-annotator"]

[mcp_servers.backlog]
# cwd = "/home/simone/projects/video-annotator"
enabled = false
