default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: repo-format-check
        name: repo format check
        entry: npm run format:check
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: repo-lint-fix
        name: repo lint fix
        entry: npm run lint:fix
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: repo-lint
        name: repo lint
        entry: npm run lint
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: repo-typecheck
        name: repo typecheck
        entry: npm run typecheck
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: repo-unit-tests
        name: repo unit tests
        entry: npm run test:unit
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: repo-integration-tests
        name: repo integration tests
        entry: npm run test:integration
        language: system
        pass_filenames: false
        stages: [pre-push]
