"""Backend service modules for milestone-01 local workflows."""

from .frame_annotations import (
    FrameAnnotationNotFoundError,
    InvalidBoxCoordinatesError,
    delete_frame_annotation_mask,
    delete_object_annotation_masks,
    get_frame_annotation_mask_path,
    list_frame_annotations,
)
from .manual_frame_annotations import (
    ManualFrameAnnotationNotFoundError,
    ManualFrameAnnotationObjectTrackNotFoundError,
    ManualFrameAnnotationVideoNotFoundError,
    delete_manual_frame_annotation,
    upsert_manual_frame_annotation,
)
from .object_tracks import ObjectTrackNotFoundError, create_object_track, delete_object_track
from .review_summaries import (
    InvalidReviewSummaryRangeError,
    ObjectTrackSummaryNotFoundError,
    ReviewState,
    SelectedObjectSummaryRecord,
    TrackSummaryRecord,
    VideoReviewSummaryRecord,
    VideoWithReviewSummaryRecord,
    get_indexed_video_with_review_summary,
    get_selected_object_summary,
    list_indexed_videos_with_review_summary,
)
from .sam2 import (
    InvalidPropagationRangeError,
    JobCancelResult,
    JobNotFoundError,
    JobStatusResult,
    Sam2PromptResult,
    Sam2PropagationFrameResult,
    Sam2PropagationJobResult,
    Sam2PropagationMaskResult,
    Sam2RuntimeDependencyError,
    Sam2RuntimeExecutionError,
    Sam2RuntimeNotConfiguredError,
    Sam2RuntimeUnavailableError,
    Sam2Service,
    Sam2SessionNotFoundError,
    Sam2SessionResult,
    Sam2VideoNotFoundError,
    Sam2VideoSourceNotAvailableError,
    close_sam2_session,
    create_or_reuse_sam2_session,
    get_job_status,
    get_sam2_service,
    prompt_sam2_box,
    refine_sam2_mask,
    request_job_cancellation,
    start_sam2_propagation_job,
)
from .video_catalog import get_indexed_video_by_id, list_indexed_videos
from .video_frames import (
    ExactFrameDecodeError,
    ExactFramePayload,
    FrameIndexOutOfRangeError,
    IndexedVideoNotFoundError,
    decode_exact_video_frame,
    load_exact_video_frame,
)
from .video_indexing import VideoMetadata, index_videos
from .video_manifest import VideoManifestRecord, get_video_manifest
from .video_metadata import extract_video_metadata

__all__ = [
    "ExactFrameDecodeError",
    "ExactFramePayload",
    "FrameAnnotationNotFoundError",
    "FrameIndexOutOfRangeError",
    "IndexedVideoNotFoundError",
    "InvalidBoxCoordinatesError",
    "InvalidPropagationRangeError",
    "InvalidReviewSummaryRangeError",
    "JobCancelResult",
    "JobNotFoundError",
    "JobStatusResult",
    "ManualFrameAnnotationNotFoundError",
    "ManualFrameAnnotationObjectTrackNotFoundError",
    "ManualFrameAnnotationVideoNotFoundError",
    "ObjectTrackNotFoundError",
    "ObjectTrackSummaryNotFoundError",
    "ReviewState",
    "Sam2PromptResult",
    "Sam2PropagationFrameResult",
    "Sam2PropagationJobResult",
    "Sam2PropagationMaskResult",
    "Sam2RuntimeDependencyError",
    "Sam2RuntimeExecutionError",
    "Sam2RuntimeNotConfiguredError",
    "Sam2RuntimeUnavailableError",
    "Sam2Service",
    "Sam2SessionNotFoundError",
    "Sam2SessionResult",
    "Sam2VideoNotFoundError",
    "Sam2VideoSourceNotAvailableError",
    "SelectedObjectSummaryRecord",
    "TrackSummaryRecord",
    "VideoManifestRecord",
    "VideoMetadata",
    "VideoReviewSummaryRecord",
    "VideoWithReviewSummaryRecord",
    "close_sam2_session",
    "create_object_track",
    "create_or_reuse_sam2_session",
    "decode_exact_video_frame",
    "delete_frame_annotation_mask",
    "delete_manual_frame_annotation",
    "delete_object_annotation_masks",
    "delete_object_track",
    "extract_video_metadata",
    "get_frame_annotation_mask_path",
    "get_indexed_video_by_id",
    "get_indexed_video_with_review_summary",
    "get_job_status",
    "get_sam2_service",
    "get_selected_object_summary",
    "get_video_manifest",
    "index_videos",
    "list_frame_annotations",
    "list_indexed_videos",
    "list_indexed_videos_with_review_summary",
    "load_exact_video_frame",
    "prompt_sam2_box",
    "refine_sam2_mask",
    "request_job_cancellation",
    "start_sam2_propagation_job",
    "upsert_manual_frame_annotation",
]
